service:
    spark-processor:
        build:
            context: ../../data_processing/
            dockerfile: Dockerfile
        container_name: spark-processor
        image: spark-processor:latest
        networks:
            - hdfs_network
            - spark_network
        environment:
            - SPARK_MASTER_URL=spark://spark-master:7077
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - SPARK_DRIVER_MEMORY=2g
            - SPARK_EXECUTOR_MEMORY=2g
        depends_on:
            - spark-master
networks:
    hdfs_network:
        external: true
        name: hdfs_network
    spark_network:
        name: spark_network
        external: true
