version: '3.8'
services:
    spark-master:
        image: bitnami/spark:3.4.1
        container_name: spark-master
        environment:
            - SPARK_MODE=master
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        ports:
            - '7077:7077'
            - '8181:8080' # Spark UI
        volumes:
            - ../../data_processing/spark/jobs:/opt/bitnami/spark/jobs
        networks:
            - hdfs_network
            - spark_network

    spark-worker-1:
        image: bitnami/spark:3.4.1
        container_name: spark-worker1
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        volumes:
            - ../../data_processing/spark/jobs:/opt/bitnami/spark/jobs
        depends_on:
            - spark-master
        networks:
            - hdfs_network
            - spark_network

    spark-worker-2:
        image: bitnami/spark:3.4.1
        container_name: spark-worker2
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        volumes:
            - ../../data_processing/spark/jobs:/opt/bitnami/spark/jobs
        depends_on:
            - spark-master
        networks:
            - hdfs_network
            - spark_network

    jupyter:
        build:
            context: ../../data_processing
            dockerfile: notebooks/Dockerfile
        container_name: jupyter
        ports:
            - '8888:8888'
        volumes:
            - ../../data_processing/notebooks:/home/jovyan/work
        networks:
            - hdfs_network
            - spark_network

networks:
    hdfs_network:
        # external: true
        # name: hdfs_network
    spark_network:
        name: spark_network
