services:
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "7077:7077"
      - "8181:8080"  # Spark UI, tránh trùng với Airflow 8080
    networks:
      - hdfs_network

  spark-worker-1:
    image: bitnami/spark:3.4.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - spark-master
    networks:
      - hdfs_network

  spark-worker-2:
    image: bitnami/spark:3.4.1
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - spark-master
    networks:
      - hdfs_network

  spark-job:
    build:
      context: ../
      dockerfile: spark_jobs/Dockerfile
    container_name: spark-job
    depends_on:
      - spark-master
      # - hdfs-namenode
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ../spark_jobs:/app
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark-master:7077
      --deploy-mode client
      /app/preview_hdfs_data.py
    networks:
      - hdfs_network

networks:
  hdfs_network:
